#======================================#
#                                      #
#      Authentication Requests         #
#                                      #
#======================================#

GET http://localhost:4001/users

###

# CREATE A NEW ACCOUNT (done)
POST http://localhost:4001/users
Content-Type: application/json

 {
    "username": "Sam",
    "password": "password",
    "email": "test@1234.com"
 }

###

# LOGIN TO ACCOUNT
POST http://localhost:4001/login
Content-Type: application/json

{
    "password": "password",
    "email": "test@1234.com"
}

###

# REFRESH ACCESS TOKEN (requires refresh token)
POST http://localhost:4001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhbSIsInBhc3N3b3JkIjoiJDJiJDEwJGhhbE8uRUdRbTMvU0p6ajZXUDlMTU8zbVhjaWUyRnBWd2w5dGpvSGNEdlRFYkZoZGFuckFpIiwiZW1haWwiOiJ0ZXN0QDEyMzQuY29tIiwiaWF0IjoxNjY2MjYwNjU1fQ.iD4Rek9KE_5uC_CIpxymFhJA9XLGjHHkHszUKsm-OE0"
}


###

# LOGOUT OF ACCOUNT (requires refresh token)
DELETE http://localhost:4001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhbSIsInBhc3N3b3JkIjoiJDJiJDEwJGgycmNQNXlPbUtVWXpIcjBCRlQvWk8yMWZST0RHNThweER6M0pnLy94ZG5iTVlUSjk3bThHIiwiZW1haWwiOiJ0ZXN0QDEyMzQuY29tIiwiaWF0IjoxNjYzMTEwNDAzfQ.v3LiS1mniBMwwXsqVtlF1lmeMFNDLooUUjw3p-t2OTc"
}


###

# ==========================#
#                           #
#      API Requests         #
#                           #
# ==========================#

# GET ALL POSTS FROM CURRENT USER (requires a valid access token)
GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAMTIzNC5jb20iLCJpYXQiOjE2NjYyNjA3NzcsImV4cCI6MTY2NjI2MDc5N30.SiZTAR5skcjN6yOTkqR1MDyfe240FfCv75Lcz3ZIKsk
###